---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: bXktZGItY29ubmVjdGlvbi5leGFtcGxlLmNvbTozMzA2
    password: bXlmYW5jeXBhc3N3b3Jk
    username: bXlmYW5jeXVzZXI=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque
